In [18]:
import pandas as pd
df3 = pd.read_csv('data/final_restaurant.csv', index_col=0)
# df3 = pd.read_csv('data/merged_restaurant_data.csv')

In [3]:
df3.query('식당이름=="청춘조개회루프탑"')

,Unnamed: 0,id,예약,음식종류,식당이름,리본개수,전화번호,영업시간_평일,영업종료_평일,영업시간_주말,...,리뷰_상세,리뷰_요약,리뷰_평가,좌석_수,룸_수,체인점여부,리뉴얼여부,대표점여부,지점여부,웹사이트
13128,13128,39377,예약불가능,"한식(어패류), 생선회, 조개구이",청춘조개회루프탑,0,0507-1412-5199,미등록,미등록,미등록,...,숙성회 모둠 세트와 조개구이 무한리필을 맛볼 수 있는 식당. 셀프바에는 콘치즈와 불...,정보 없음,정보 없음,미등록,미등록,True,False,정보 없음,정보 없음,https://www.instagram.com/seafood_oido/

In [24]:
str(dict(info))

"'id': 4627, '예약': '예약가능', '음식종류': '중식, 일반중식', '식당이름': '홍보각', '리본개수': 3, '전화번호': '02-531-6479', '영업시간_평일': '미등록', '영업종료_평일': '미등록', '영업시간_주말': '미등록', '영업종료_주말': '미등록', '휴무일': '연중무휴', '앱사용여부': True, '주차가능여부': '가능', '카드결제가능여부': 'y', '방문가능여부': nan, '메뉴정보': '스페셜코스(1인 15만원), 디너코스(A 12만원, B 16만원), 고법불도장(13만원), 모자새우(소 6만원, 대 10만원), 한알탕수육(소 4만8천원, 대 7만원), 특선냉채(2만8천원), 셰프특선수프(3만8천원), 셰프스페셜송이특찜(15만원)', '가격대': '10~15만원대', '영업시간': '12:00~15:00/18:00~21:30(마지막 주문 20:00) ', '신규오픈날짜': '2007년 ', '도로명주소': '서울특별시 강남구 봉은사로 130', '시': '서울특별시', '구': '강남구', '도로명': '동호로', '리뷰_상세': '국내 중식의 대가인 여경래 셰프가 2023년 이전하여 오픈한 중식 파인 다이닝 레스토랑. 고급스러운 분위기의 인테리어에서 정통 중식을 맛볼 수 있다. 여경래 셰프의 시그니처 메뉴인 불도장, 모자새우 등을 선보인다.', '리뷰_요약': '국내 중식의 대가인 여경래 셰프가 2023년 이전하여 오픈한 중식 파인 다이닝 레스토랑. 고급스러운 분위기의 인테리어에서 정통 중식을 맛볼 수 있다. 여경래 셰프의 시그니처 메뉴인 불도장, 모자새우 등을 선보인다.', '리뷰_평가': '정보 없음', '좌석_수': '64', '룸_수': '6개(2, 3, 4, 6, 8, 12석)', '체인점여부': False, '리뉴얼여부': False, '대표점여부': '정보 없음', '지점여부': '정보 없음', '웹사이트': 'https://www.instagram.com/hongbogak_official/'"

In [26]:
from langchain_core.documents import Document
raw_df = df3.head()
doc_list = []
for _, info in raw_df.iterrows():
    doc_list.append(Document(page_content=str(dict(info)), metadata=dict(info)))

doc_list[0].page_content

"{'id': 4627, '예약': '예약가능', '음식종류': '중식, 일반중식', '식당이름': '홍보각', '리본개수': 3, '전화번호': '02-531-6479', '영업시간_평일': '미등록', '영업종료_평일': '미등록', '영업시간_주말': '미등록', '영업종료_주말': '미등록', '휴무일': '연중무휴', '앱사용여부': True, '주차가능여부': '가능', '카드결제가능여부': 'y', '방문가능여부': nan, '메뉴정보': '스페셜코스(1인 15만원), 디너코스(A 12만원, B 16만원), 고법불도장(13만원), 모자새우(소 6만원, 대 10만원), 한알탕수육(소 4만8천원, 대 7만원), 특선냉채(2만8천원), 셰프특선수프(3만8천원), 셰프스페셜송이특찜(15만원)', '가격대': '10~15만원대', '영업시간': '12:00~15:00/18:00~21:30(마지막 주문 20:00) ', '신규오픈날짜': '2007년 ', '도로명주소': '서울특별시 강남구 봉은사로 130', '시': '서울특별시', '구': '강남구', '도로명': '동호로', '리뷰_상세': '국내 중식의 대가인 여경래 셰프가 2023년 이전하여 오픈한 중식 파인 다이닝 레스토랑. 고급스러운 분위기의 인테리어에서 정통 중식을 맛볼 수 있다. 여경래 셰프의 시그니처 메뉴인 불도장, 모자새우 등을 선보인다.', '리뷰_요약': '국내 중식의 대가인 여경래 셰프가 2023년 이전하여 오픈한 중식 파인 다이닝 레스토랑. 고급스러운 분위기의 인테리어에서 정통 중식을 맛볼 수 있다. 여경래 셰프의 시그니처 메뉴인 불도장, 모자새우 등을 선보인다.', '리뷰_평가': '정보 없음', '좌석_수': '64', '룸_수': '6개(2, 3, 4, 6, 8, 12석)', '체인점여부': False, '리뉴얼여부': False, '대표점여부': '정보 없음', '지점여부': '정보 없음', '웹사이트': 'https://www.instagram.com/hongbogak_official/'}"

In [15]:
df3.iloc[0:10, 0:10]

,Unnamed: 0,id,예약,음식종류,식당이름,리본개수,전화번호,영업시간_평일,영업종료_평일,영업시간_주말
0,0,4627,예약가능,"중식, 일반중식",홍보각,3,02-531-6479,미등록,미등록,미등록
1,1,29083,예약가능,"컨템포러리, 이노베이티브퀴진, 분자요리, 이탈리아식",쵸이닷,3,02-518-0318,12:00,22:30,미등록
2,2,28946,예약가능,프랑스식,더그린테이블,3,02-591-2672,미등록,미등록,미등록
3,3,4963,예약가능,"한식(육류), 소갈비, 소고기구이, 한우오마카세",명월관,3,02-6330-9050,미등록,미등록,미등록
4,4,859,예약가능,프랑스식,콘티넨탈,3,02-2230-3369,미등록,미등록,미등록
5,5,27144,예약가능,"한식(일반한식), 모던한식, 뉴코리안",밍글스,3,02-515-7306,미등록,미등록,미등록
6,6,26944,예약가능,컨템포러리,스와니예,3,02-3477-9386,미등록,미등록,미등록
7,7,30639,예약가능,"중식, 일반중식",다이닝마,3,02-518-7400,미등록,미등록,미등록
8,8,952,예약가능,"한식(일반한식), 모던한식",한국의집,3,02-2266-9101,미등록,미등록,미등록
9,9,29427,예약가능,"일식, 가이세키",미토우,3,0507-1306-9914,미등록,미등록,미등록

In [16]:
df3.iloc[0:10, 11:21]

,휴무일,앱사용여부,주차가능여부,카드결제가능여부,방문가능여부,메뉴정보,가격대,영업시간,신규오픈날짜,도로명주소
0,연중무휴,True,가능,y,NaN,"스페셜코스(1인 15만원), 디너코스(A 12만원, B 16만원), 고법불도장(13...",10~15만원대,12:00~15:00/18:00~21:30(마지막 주문 20:00),2007년,서울특별시 강남구 봉은사로 130
1,연중무휴,False,가능,y,청담사거리 앞. 버버리코리아 옆 건물,"런치코스(3코스 7만\r\n\8천원, 4코스 9만8천원), 디너코스(19만8천원),...",15~25만원대,12:00~15:00/18:30~22:00,2017년 03월 18일,서울특별시 강남구 도산대로 457
2,"월, 화요일, 명절 휴무",False,가능,y,안국역 3번 출구에서 직진 후 아라리오 뮤지엄 5층에 위치,"런치코스(17만원), 디너코스(27만원), 와인페어링(변동)",15~25만원대,12:00~15:00/18:00~22:00 | 일요일 12:00~15:00/18:0...,2009년 11월 14일,서울특별시 종로구 율곡로 83
3,연중무휴,True,가능,y,광장동 쉐라톤그랜드워커힐 내,"생등심(180g 9만8천원), 생갈비(160g 11만3천원), 한우육회(150g 6...",15~25만원대,12:00~15:00/17:30~21:00,1982년,서울특별시 광진구 워커힐로 177
4,연중무휴,False,가능,y,동대입구역 5번출구로 나오면 장충동 신라호텔 23층,"런치코스(3코스 12만원, 4코스 14만원, 5코스 15만5천원), 디너코스(30만원)",25만원 이상,12:00~14:30/17:30~21:30,1985년 07월,서울특별시 중구 동호로 249
5,"일, 월요일 정기 휴무",False,발레 파킹,y,학동사거리에서 압구정로데오역 방향으로 직진. 버거킹에서 우회전 후 커피빈에서 좌회전,"런치코스(28만원), 디너코스(34만원), 전통주페어링(17만원), 시그니처페어링(...",25만원 이상,12:00~15:00/18:00~22:00,2014년 05월 05일,서울특별시 강남구 도산대로67길 19
6,월요일 휴무. 명절 휴무,False,가능(신사스퀘어 주차장 이용),y,NaN,"런치코스(21만원), 디너코스(32만원)",25만원 이상,12:00~15:00/18:00~22:00 (마지막 주문 19:30),2013년 12월 24일,서울특별시 강남구 강남대로 652
7,"일요일, 명절 당일 휴무",False,발레 파킹,y,도산공원 사거리에서 BMW 강남전시장 골목으로 진입하면 우측,"옌바오츠코스(99만원), 만한전석코스(75만원), 다이닝마코스(A 29만원, B 3...",25만원 이상,11:30~14:30(마지막 주문 14:00)/17:30~21:30(마지막 주문 2...,2019년 11월 11일,서울특별시 강남구 언주로152길 8
8,"월요일, 명절 연휴 휴무",False,가능,y,충무로역 3번 출구에서 GS칼텍스 끼고 우회전,"1957반상(8만8천원), 신선로정식(A 만찬 20만원, B 오찬 10만원), 한국...",5~10만원대,12:00~15:00(마지막 주문 13:00)/18:00~22:00(마지막 주문 1...,1957년 06월 24일,서울특별시 중구 퇴계로36길 10
9,"일, 월요일 휴무",False,발레 파킹,y,NaN,미토우코스(28만원~30만원),25만원 이상,18:00~22:00,2018년 02월,서울특별시 강남구 도산대로70길 24

In [17]:
df3.iloc[0:10, 21:31]

,시,구,도로명,리뷰_상세,리뷰_요약,리뷰_평가,좌석_수,룸_수,체인점여부,리뉴얼여부
0,서울특별시,강남구,동호로,국내 중식의 대가인 여경래 셰프가 2023년 이전하여 오픈한 중식 파인 다이닝 레스...,국내 중식의 대가인 여경래 셰프가 2023년 이전하여 오픈한 중식 파인 다이닝 레스...,정보 없음,64,"6개(2, 3, 4, 6, 8, 12석)",False,False
1,서울특별시,강남구,미등록,최현석 셰프의 크리에이티브한 요리를 즐길 수 있는 레스토랑. 분자요리와 이탈리아 요...,최현석 셰프의 크리에이티브한 요리를 즐길 수 있는 레스토랑. 분자요리와 이탈리아 요...,“어디까지 발전할 수 있을지 진심으로 기대되는 곳.” “음식 너무나 재밌었어요.”,미등록,미등록,False,False
2,서울특별시,종로구,미등록,김은희 셰프가 운영하는 프렌치 레스토랑. 사계절에 따라 변화하는 우리나라 식재료로 ...,김은희 셰프가 운영하는 프렌치 레스토랑. 사계절에 따라 변화하는 우리나라 식재료로 ...,“음식의 결 하나하나에서 섬세한 정성이 듬뿍 느껴진다. 신선한 재료들이 훌륭하게 조...,미등록,미등록,False,False
3,서울특별시,광진구,워커힐로,"워커힐호텔 내 한옥 분위기의 별채로 있는, 주변 경치가 아름다운 숯불구이 전문점. ...","워커힐호텔 내 한옥 분위기의 별채로 있는, 주변 경치가 아름다운 숯불구이 전문점. ...",정보 없음,300,4개,False,False
4,서울특별시,중구,동호로,"정통 유럽 스타일의 프렌치 레스토랑으로, 40여 년의 역사를 자랑하는, 서울에서 오...","정통 유럽 스타일의 프렌치 레스토랑으로, 40여 년의 역사를 자랑하는, 서울에서 오...",“최고의 레스토랑이다.” “분위기가 상당히 모던하고 세련된 느낌. 재료의 질이 최상...,70석,1개,False,False
5,서울특별시,강남구,선릉로,국내외에서 이름을 드높이고 있는 강민구 셰프의 뉴코리안 레스토랑. 사찰음식과 한식 ...,국내외에서 이름을 드높이고 있는 강민구 셰프의 뉴코리안 레스토랑. 사찰음식과 한식 ...,“창의적인 한식에 심혈을 기울인 느낌.” “제대로 된 뉴코리안을 느낄 수 있는 곳....,미등록,미등록,False,False
6,서울특별시,강남구,반포대로39길,프렌치에 한국적인 요소를 가미한 컨템포러리 레스토랑. 에피소드라는 이름으로 시즌별로...,프렌치에 한국적인 요소를 가미한 컨템포러리 레스토랑. 에피소드라는 이름으로 시즌별로...,“와인페어링과 함께하는 만찬은 한편의 뮤지컬같다.” “창의적이고 예술가적 기질이 뛰...,미등록,미등록,False,False
7,서울특별시,강남구,미등록,"중국 3대 진미로 뽑히는 샥스핀을 전문으로 하는 고급 중식당으로, 룸으로만 구성되어...","중국 3대 진미로 뽑히는 샥스핀을 전문으로 하는 고급 중식당으로, 룸으로만 구성되어...",정보 없음,미등록,미등록,False,False
8,서울특별시,중구,퇴계로,조선왕조 궁궁음식 기반의 전통 한식을 품격 있게 담아낸 궁중음식 파인 다이닝을 선보...,고풍스러운 한옥에서 국악과 함께 다양한 궁중요리 코스를 즐길 수 있는 곳이다. 궁중...,정보 없음,미등록,미등록,False,False
9,서울특별시,강남구,논현로151길,"일본에서 수련 후 귀국한 권영운, 김보미 오너셰프의 일본요리 전문점. 담담하면서도 ...",정보 없음,정보 없음,미등록,미등록,False,False

In [18]:
df3.iloc[0:10, 31:41]

   대표점여부   지점여부                                               웹사이트
0  정보 없음  정보 없음      https://www.instagram.com/hongbogak_official/
1  정보 없음  정보 없음        https://www.instagram.com/choidot_official/
2  정보 없음  정보 없음  http://thegreentable.co.kr/, https://www.insta...
3  정보 없음  정보 없음  https://www.walkerhill.com/grandwalkerhillseou...
4  정보 없음  정보 없음  https://www.shilla.net/seoul/dining/viewDining...
5  정보 없음  정보 없음  http://www.restaurant-mingles.com, https://www...
6  정보 없음  정보 없음  http://soignerestaurantgroup.com, https://www....
7  정보 없음  정보 없음                                                미등록
8  정보 없음  정보 없음  http://www.koreahouse.or.kr/, https://www.inst...
9  정보 없음  정보 없음               https://www.instagram.com/mitouseoul

In [19]:
df3.iloc[0:10, 41:51]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]